spring:
  application:
    name: mscreditappraiser
#  datasource:
#    url: jdbc:h2:mem:mscreditappraiser
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 0 # para subir em uma porta randonica
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}